### PR TITLE
Fix signatures of FIDO keys, add ED25519 support

### PR DESCRIPTION
**Pull request by maleadt**
Fingerprints were wrong because it left out the `sk_application` field. Now they're correct cfr. what `ssh-keygen` reports:

```
$ ssh-keygen -l -f tests/test-keys/id_ecdsa_sk_sha2_nistp256.pub
256 SHA256:lJ9TEvCO2FVQ443DnK7UQsA0sR44xXikW9p8gzH/q7s yubikey-5c-test-wbrown (ECDSA-SK)
```

I also added support for ed25519-sk keys (the main reason I looked at this code).

### CODE REVIEW

**Comment by dnaeon** [comment]
Hey, @maleadt !

Thanks for the PR! Could you please also bump the version?

Thanks!

**Comment by maleadt** [comment]
Sure, I bumped it to 0.3.2. Or do you want 0.4 (for a strict interpretation of semver)?

**Comment by dnaeon** [comment]
Thanks!

Tagged and published on crates.io.

**Comment by maleadt** [comment]
Thanks for the quick turnaround!

**Pull request merged**
